BACKLIGHT_ENABLE = no
RGBLIGHT_ENABLE = no
AUDIO_ENABLE = no
MOUSEKEY_ENABLE = yes
VIA_ENABLE = yes
POINTING_DEVICE_ENABLE = yes
CONSOLE_ENABLE = no         # Console for debug
LTO_ENABLE = yes
QMK_SETTINGS = no

SRC += v99slim.c
